/** Deterministic workflow evidence. No transcript bodies, commands, paths, thoughts or model advice. */
export const WORKFLOW_VERSION = 1 as const;
export const WORKFLOW_METRICS = [
  "wakeCopies", "wakeGroups", "providerErrors", "providerBursts",
  "duplicateDeliveries", "duplicateBytes", "abortedNoFinal", "abortedConversations",
  "testCalls", "pairedTestCalls", "testExitKnown", "testExitZero", "testErrored",
  "testTimeouts", "testFiltered", "testForcedExit", "mutations", "nonTestNamedMutations",
  "firstTestAfterMutation", "baselineReads", "startupConversations", "startupSystemBytes",
  "startupTaskBytes", "assistantRecords", "tokenComplete", "costComplete", "reasoningComplete",
  "compactions", "compactionPairs", "beforePrompt", "afterPrompt", "opaqueRecords",
] as const;
export type WorkflowMetric = typeof WORKFLOW_METRICS[number];
export type WorkflowKind = "wakes-errors" | "duplicate-delivery" | "missing-handoff" |
  "verification" | "chronology" | "startup" | "roles" | "compaction" | "telemetry";
export interface WorkflowUsage {
  input?: number; output?: number; cacheRead?: number; cacheWrite?: number;
  reasoning?: number; cost?: number;
}
export interface WorkflowCall {
  id: string;
  name: string;
  test?: boolean;
  filtered?: boolean;
  forcedExit?: boolean;
  mutation?: boolean;
  testNamedPath?: boolean;
  baselineRead?: boolean;
}
/** One physical JSONL record. Optional means unknown, never implicit zero. */
export interface WorkflowRecord {
  id: string;
  parentId?: string;
  line: number;
  at?: number;
  kind: "session" | "metadata" | "context-edit" | "system" | "user" | "notice" | "assistant" | "tool-result" | "compaction" | "opaque";
  role?: string;
  provider?: string;
  stop?: string;
  finalText?: boolean;
  textBytes?: number;
  textHash?: string;
  deliveryHash?: string;
  deliveryBytes?: number;
  wakeHash?: string;
  providerError?: boolean;
  calls?: WorkflowCall[];
  resultFor?: string;
  isError?: boolean;
  exitCode?: number;
  timeout?: boolean;
  usage?: WorkflowUsage;
}
export interface WorkflowCapture {
  version: 1;
  records: WorkflowRecord[];
  /** Records intentionally not normalized (large/unsupported records or the record cap). */
  omittedRecords: number;
}
export interface WorkflowInput {
  /** Same canonical source order as usage accounting. */
  sessionId: string;
  capture?: WorkflowCapture;
}
export interface WorkflowEvidence {
  kind: WorkflowKind;
  session: string;
  line: number;
  relatedLine?: number;
}
export interface WorkflowDay {
  /** Local YYYY-MM-DD, matching the usage rollup. */
  day: string;
  metrics: Partial<Record<WorkflowMetric, number>>;
  /** Bounded source references; no excerpts or source paths. */
  evidence: WorkflowEvidence[];
}
export interface WorkflowRoleDay {
  day: string;
  /** Explicit declaration only; otherwise "unknown". Never inferred from task subject. */
  role: string;
  requests: number;
  cost: number;
  costKnown: number;
  tokensKnown: number;
  input: number;
  output: number;
  cacheRead: number;
  cacheWrite: number;
  reasoning: number;
  reasoningKnown: number;
}
/** Optional pi-hud/usage v1 rollup member. Old clients ignore it; absent means unavailable. */
export interface WorkflowSnapshot {
  version: 1;
  days: WorkflowDay[];
  roles: WorkflowRoleDay[];
  coverage: {
    filesWithRecords: number;
    filesWithoutRecords: number;
    omittedRecords: number;
    /** Includes undated, genuinely uninspected records, not known metadata entries. */
    opaqueRecords?: number;
  };
}
/** Surface adapter product, generated by code, not a model. */
export interface WorkflowInsight {
  kind: WorkflowKind;
  headline: string;
  detail: string;
  evidence: WorkflowEvidence[];
}
